linters:
  enable:
    - asciicheck
    - godot
    - cyclop
    - mnd

linters-settings:
  cyclop:
    max-complexity: 5

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - cyclop